---
cor: 
  hosts: 
    lax_cor_r1:
      ansible_host: 192.168.2.50
    nyc_cor_r1:
      ansible_host: 192.168.2.60
  vars: 
      ansible_network_os: cisco.nxos.nxos 

edg: 
  hosts: 
    lax_edg_r1: 
      ansible_host: 192.168.2.51
    lax_edg_r2:
      ansible_host: 192.168.2.52
    nyc_edg_r1: 
      ansible_host: 192.168.2.61
    nyc_edg_r2: 
      ansible_host: 192.168.2.62
  vars: 
    ansible_network_os: cisco.ios.ios 

all: 
  children: 
    cor:
    edg: 
  vars: 
    ansible_user: "{{ lookup('env', 'ansible_user') }}"
    ansible_ssh_pass: "{{ lookup('env', 'ansible_ssh_pass') }}"
    ansible_connection: ansible.netcommon.network_cli 
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ lookup('env', 'ansible_become_pass') }}" 
