---
stage_cor: 
  hosts: 
    stage_lax_cor_r1: 
      ansible_host: 192.168.2.70
      ansible_network_os: cisco.nxos.nxos

stage_edg: 
  hosts: 
    stage_lax_edg_r1: 
      ansible_host: 192.168.2.71
    stage_lax_edg_r2:
      ansible_host: 192.168.2.72
  vars: 
    ansible_network_os: cisco.ios.ios

stage_all: 
  children: 
    stage_cor:
    stage_edg: 
  vars: 
    ansible_user: "{{ lookup('env', 'ansible_user') }}"
    ansible_ssh_pass: "{{ lookup('env', 'ansible_ssh_pass') }}"
    ansible_connection: ansible.netcommon.network_cli 
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ lookup('env', 'ansible_become_pass') }}" 

    



